#!/usr/local/bin/ansible-playbook
---
- name: Install AWS CLI v2
  hosts: localhost
  connection: local

  tasks:

    - name: Install OS packages
      package:
        name: '{{ item }}'
      loop:
        - curl
        - unzip

    - name: Get AWS CLI archive for Linux
      command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      args:
        creates: /tmp/awscliv2.zip

    - name: Unzip the archive
      command: unzip awscliv2.zip
      args:
        chdir: /tmp
        creates: /tmp/aws

    - name: Install AWS CLI
      command: ./install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      args:
        chdir: /tmp/aws
        creates: /usr/local/bin/aws
