#!/usr/bin/env ansible-playbook
---
- name: Install Docker
  hosts: my_hosts
  vars:
    docker_compose_version: v2.35.0
    ansible_become: True
  tasks:
    - name: Install OS packages
      apt:
        update_cache: True
        name: '{{ item }}'
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Get GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: Add APT repo x86_64
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable"
      when: ansible_machine == "x86_64"

    - name: Add APT repo aarch64
      apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable"
      when: ansible_machine == "aarch64"

    - name: Create config folder
      file:
        path: /etc/docker
        state: directory

    - name: Setup daemon.json file
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "bip": "192.168.127.5/24",
            "default-address-pools": [
              {
                "base": "192.168.128.0/17",
                "size": 24
              }
            ]
          }
      notify: restart docker

    - name: Install Docker packages
      apt:
        update_cache: True
        name: '{{ item }}'
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: True

    - name: Install docker-compose
      command: curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64 -o "docker-compose"
      args:
        chdir: /usr/local/bin
        creates: /usr/local/bin/docker-compose
      when: ansible_machine == "x86_64"

    - name: Install docker-compose
      command: curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-aarch64 -o "docker-compose"
      args:
        chdir: /usr/local/bin
        creates: /usr/local/bin/docker-compose
      when: ansible_machine == "aarch64"

    - name: Set the execute bit on docker-compose
      file:
        path: /usr/local/bin/docker-compose
        mode: 0755

    - name: Add user to docker group
      debug:
        msg: "example command: usermod -aG docker <user name>"

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
