---
- name: Install Docker
  hosts: my_hosts
  gather_facts: True
  become: True

  vars:
    docker_arch_map:
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Install prerequisite packages
      apt:
        update_cache: True
        name: '{{ item }}'
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set Docker GPG key permissions
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: 'a+r'

    - name: Add Docker APT repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "deb [arch={{ docker_arch_map[ansible_facts['machine']] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable\n"

    - name: Create Docker data directory
      file:
        path: /data
        state: directory
        mode: '0711'

    - name: Create Docker config folder
      file:
        path: /etc/docker
        state: directory

    - name: Setup daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "data-root": "/data",
            "log-driver": "json-file",
            "bip": "192.168.127.5/24",
            "default-address-pools": [
              {
                "base": "192.168.128.0/17",
                "size": 24
              }
            ]
          }
      notify: restart docker

    - name: Install Docker packages
      apt:
        update_cache: True
        name: '{{ item }}'
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: True

    - name: Add user to docker group
      debug:
        msg: "example command: usermod -aG docker <user name>"

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
