---
- name: Install GitHub tools
  hosts: my_hosts
  tasks:
  - name: Install gpg package
    package:
      name: gpg

  - name: Get GPG key
    apt_key:
      url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
      state: present

  - name: Add APT repo x86_64
    apt_repository:
      repo: "deb [arch=amd64] https://cli.github.com/packages stable main"
    when: ansible_machine == "x86_64"

  - name: Add APT repo aarch64
    apt_repository:
      repo: "deb [arch=arm64] https://cli.github.com/packages stable main"
    when: ansible_machine == "aarch64"

  - name: Install tools
    apt:
      update_cache: True
      name: '{{ item }}'
    loop:
      - gh
