---
- name: Install Golang
  hosts: my_hosts
  vars:
    golang_version: 1.22.2

  tasks:
    - name: Get Golang x86_64
      command: curl -L "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz" -o golang.tar.gz
      args:
        chdir: /tmp
        creates: /tmp/golang.tar.gz
      when: ansible_machine == "x86_64"

    - name: Get Golang aarch64
      command: curl -L "https://go.dev/dl/go{{ golang_version }}.linux-arm64.tar.gz" -o golang.tar.gz
      args:
        chdir: /tmp
        creates: /tmp/golang.tar.gz
      when: ansible_machine == "aarch64"

    - name: Install Golang
      command: tar -C /usr/local -xzf golang.tar.gz
      args:
        chdir: /tmp
        creates: /usr/local/go/bin/go
      become: true

    - name: Link go to /usr/local/bin/go
      file:
        src: /usr/local/go/bin/go
        dest: /usr/local/bin/go
        state: link
