#!/usr/bin/env ansible-playbook
---
- name: Install Hashicorp tools
  hosts: my_hosts

  vars:
    terraform_docs_version: v0.20.0

  tasks:
  - debug:
      msg: 'user {{ ansible_env.SUDO_USER }} ran the sudo to become root'

  - name: Install gpg package
    package:
      name: gpg
    become: True

  - name: Get GPG key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
    become: True

  - name: Add APT repo
    apt_repository:
      repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    when: ansible_machine == "x86_64"
    become: True

  - name: Add APT repo
    apt_repository:
      repo: "deb [arch=arm64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    when: ansible_machine == "aarch64"
    become: True

  - name: Install tools
    apt:
      update_cache: True
      name: '{{ item }}'
      state: latest
    loop:
      - packer
      - terraform
      - vault
    become: True

  - name: Download Terraform Docs x86_64
    command: curl -L "https://github.com/terraform-docs/terraform-docs/releases/download/{{ terraform_docs_version }}/terraform-docs-{{ terraform_docs_version }}-linux-amd64.tar.gz" -o "terraform-docs.tar.gz"
    args:
      chdir: /tmp
      creates: /tmp/terraform-docs.tar.gz
    when: ansible_machine == "x86_64"

  - name: Download Terraform Docs aarch64
    command: curl -L "https://github.com/terraform-docs/terraform-docs/releases/download/{{ terraform_docs_version }}/terraform-docs-{{ terraform_docs_version }}-linux-arm64.tar.gz" -o "terraform-docs.tar.gz"
    args:
      chdir: /tmp
      creates: /tmp/terraform-docs.tar.gz
    when: ansible_machine == "aarch64"

  - name: Extract terraform-docs.tar.gz
    command: tar -C /usr/local/bin --no-same-owner -zxf terraform-docs.tar.gz terraform-docs
    args:
      chdir: /tmp
      creates: /usr/local/bin/terraform-docs
    become: True

  - name: Create bash_aliases
    file:
      path: "/home/{{ ansible_env.SUDO_USER }}/.bash_aliases"
      state: touch
    changed_when: false

  - name: Setup aliases
    lineinfile:
      path: "/home/{{ ansible_env.SUDO_USER }}/.bash_aliases"
      line:  '{{ item }}'
    loop:
      - alias tf='terraform'
      - alias tfdocs='terraform-docs'
