#!/usr/local/bin/ansible-playbook
---
- name: Install Helm
  hosts: localhost
  connection: local

  tasks:

    - name: Get Helm install script
      command: curl "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3" -o "/tmp/get_helm.sh"
      args:
        creates: /tmp/get_helm.sh

    - name: Execute the install script
      command: bash /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
